name: Build Firmware

permissions:
  contents: read

on:
  push:
    branches:
    - 'user-shearn89'

jobs:
  lint:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli

    steps:
    - name: Disable safe.directory check
      run : git config --global --add safe.directory '*'

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run QMK
      run: qmk compile -kb dztech/dz60rgb_ansi/v2_1 -km shearn89

    - name: Archive firmware
        uses: actions/upload-artifact@v4
        with:
          name: FLASH.bin
          path: dztech_dz60rgb_ansi_v2_1_shearn89.bin
